/**
 * Marketplace: Pept Trade x Research Only
 * Catalog + kit prices mirror the Research Only product line (10-vial kits, >99% purity).
 * Checkout is on-chain: pay the listed price in Robinhood testnet USDC via MarketplaceShop.
 * Research Only is a brand partnership label; products are not deep-linked to their store.
 */

export const MARKETPLACE_BRAND = {
  name: "Pept Trade x Research Only",
  shortName: "PT x RO",
} as const;

export const RESEARCH_ONLY = {
  name: "Research Only",
  shortName: "RO",
  /** Partnership brand (catalog source); checkout is PEPT Trade USDC, not external. */
  url: "https://researchonly.io",
  shopUrl: "https://researchonly.io/shop/",
  aboutUrl: "https://researchonly.io/about/",
  tagline: "Research-grade peptides · >99% purity · HPLC + MS tested",
  disclaimer:
    "For research use only. Not for human or veterinary use, diagnostic, or therapeutic purposes. Demo checkout on Robinhood Chain Testnet in USDC.",
  purity: ">99%",
  testing: "HPLC + MS, every lot",
  kitNote: "All compounds sold in kits of 10 vials",
  shipping: "On-chain purchase · research use only",
  verified: true,
  region: "Global",
} as const;

export type Category = { id: string; label: string; icon: string };

/** Matches Research Only shop filters. */
export const CATEGORIES: Category[] = [
  { id: "all", label: "Everything", icon: "Hexagon" },
  { id: "weightloss", label: "Weight Loss", icon: "Flame" },
  { id: "recovery", label: "Recovery", icon: "Recycle" },
  { id: "longevity", label: "Longevity", icon: "Sparkles" },
  { id: "cognitive", label: "Cognitive", icon: "Brain" },
  { id: "aesthetic", label: "Aesthetic", icon: "Sparkle" },
];

export type Peptide = {
  id: string;
  sku: string;
  name: string;
  category: string;
  description: string;
  /** Display kit size (Research Only ships 10-vial kits). */
  kitLabel: string;
  /** Per-vial strength when known from product name, else generic. */
  dosage: string;
  purity: string;
  form: string;
  priceFrom: number;
  /** True when shop lists "from $X" (variable vial strength). */
  priceIsFrom: boolean;
  inStock: boolean;
  bestseller?: boolean;
  researchUseOnly: true;
  partnerUrl: string;
  imageUrl?: string;
  icon: string;
};

/**
 * Full Research Only product list from https://researchonly.io/shop/
 * (31 compounds as of catalog capture). Order roughly matches featured shop.
 */
export const PEPTIDES: Peptide[] = [
  {
    id: "wolverine-stack",
    sku: "RO-074",
    name: "Wolverine Stack",
    category: "recovery",
    description: "BPC-157 / TB-500 recovery pairing",
    kitLabel: "10 Vials",
    dosage: "10mg kit",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 262.4,
    priceIsFrom: true,
    inStock: true,
    bestseller: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/wolverine-stack/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Wolverine-10mg-1024x1024.webp",
    icon: "Zap",
  },
  {
    id: "glow",
    sku: "RO-072",
    name: "GLOW",
    category: "recovery",
    description: "GHK-Cu / BPC-157 / TB-500",
    kitLabel: "10 Vials",
    dosage: "70mg kit",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 434.0,
    priceIsFrom: false,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/glow/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/GLOW-70mg-1024x1024.webp",
    icon: "Sparkles",
  },
  {
    id: "cjc-ipa",
    sku: "RO-069",
    name: "CJC/Ipa",
    category: "recovery",
    description: "Paired GHRH + secretagogue blend",
    kitLabel: "10 Vials",
    dosage: "10mg kit",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 271.2,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/cjc-ipa/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/CJC-Ipa-10mg-1024x1024.webp",
    icon: "Hexagon",
  },
  {
    id: "epitalon",
    sku: "RO-055",
    name: "Epitalon",
    category: "longevity",
    description: "Tetrapeptide (Ala-Glu-Asp-Gly)",
    kitLabel: "10 Vials",
    dosage: "10mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 178.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/epitalon/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Epithalon_10mg-1024x1024.webp",
    icon: "Sparkles",
  },
  {
    id: "pt-141",
    sku: "RO-049",
    name: "PT-141",
    category: "aesthetic",
    description: "Bremelanotide, melanocortin agonist",
    kitLabel: "10 Vials",
    dosage: "10mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 183.2,
    priceIsFrom: false,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/pt-141/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/PT141_10mg-1024x1024.webp",
    icon: "Heart",
  },
  {
    id: "melanotan-ii",
    sku: "RO-048",
    name: "Melanotan II",
    category: "aesthetic",
    description: "Cyclic α-MSH analogue",
    kitLabel: "10 Vials",
    dosage: "10mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 172.2,
    priceIsFrom: false,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/melanotan-ii/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Melanotan2_10mg-1024x1024.webp",
    icon: "Sun",
  },
  {
    id: "sermorelin",
    sku: "RO-030",
    name: "Sermorelin",
    category: "recovery",
    description: "GHRH (1-29) analogue",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 167.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/sermorelin/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Sermorelin_2mg-1024x1024.webp",
    icon: "Activity",
  },
  {
    id: "ipamorelin",
    sku: "RO-029",
    name: "Ipamorelin",
    category: "recovery",
    description: "Selective GH secretagogue",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 106.2,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/ipamorelin/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Ipamorelin_2mg-1024x1024.webp",
    icon: "Hexagon",
  },
  {
    id: "kpv",
    sku: "RO-018",
    name: "KPV",
    category: "recovery",
    description: "Lysine-Proline-Valine tripeptide",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 148.0,
    priceIsFrom: true,
    inStock: true,
    bestseller: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/kpv/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/KPV_5mg-1024x1024.webp",
    icon: "Shield",
  },
  {
    id: "tb-500",
    sku: "RO-016",
    name: "TB-500",
    category: "recovery",
    description: "Thymosin Beta-4 fragment",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 159.0,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/tb-500/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/TB500_2mg-1024x1024.webp",
    icon: "Waves",
  },
  {
    id: "tirzepatide",
    sku: "RO-002",
    name: "Tirzepatide",
    category: "weightloss",
    description: "Dual GIP/GLP-1 receptor agonist",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 134.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/tirzepatide/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Tirzepatide_5mg-1024x1024.webp",
    icon: "Flame",
  },
  {
    id: "tesamorelin",
    sku: "RO-031",
    name: "Tesamorelin",
    category: "recovery",
    description: "Stabilised GHRH analogue",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 178.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/tesamorelin/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Tesamorelin_2mg-1024x1024.webp",
    icon: "Activity",
  },
  {
    id: "klow",
    sku: "RO-073",
    name: "KLOW",
    category: "recovery",
    description: "KPV / GHK-Cu / BPC-157 / TB-500",
    kitLabel: "10 Vials",
    dosage: "80mg kit",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 522.0,
    priceIsFrom: false,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/klow/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/KLOW-80mg-1024x1024.webp",
    icon: "Layers",
  },
  {
    id: "dsip",
    sku: "RO-067",
    name: "DSIP",
    category: "longevity",
    description: "Delta sleep-inducing peptide",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 117.2,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/dsip/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/DSIP_2mg-1024x1024.webp",
    icon: "Moon",
  },
  {
    id: "5-amino-1mq",
    sku: "RO-062",
    name: "5-Amino-1MQ",
    category: "longevity",
    description: "NNMT inhibitor research compound",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 145.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/5-amino-1mq/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/5-amino-1mq-5mg-1024x1024.webp",
    icon: "Atom",
  },
  {
    id: "glutathione",
    sku: "RO-060",
    name: "Glutathione",
    category: "longevity",
    description: "Reduced tripeptide antioxidant",
    kitLabel: "10 Vials",
    dosage: "400mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 112.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/glutathione/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Glutathione_400mg-1024x1024.webp",
    icon: "Shield",
  },
  {
    id: "ss-31",
    sku: "RO-057",
    name: "SS-31",
    category: "longevity",
    description: "Elamipretide, mitochondrial peptide",
    kitLabel: "10 Vials",
    dosage: "10mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 247.0,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/ss-31/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/SS31_10mg-1024x1024.webp",
    icon: "Cpu",
  },
  {
    id: "nad",
    sku: "RO-056",
    name: "NAD+",
    category: "longevity",
    description: "Nicotinamide adenine dinucleotide",
    kitLabel: "10 Vials",
    dosage: "250mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 141.4,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/nad/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/NAD_250mg-1024x1024.webp",
    icon: "Battery",
  },
  {
    id: "pinealon",
    sku: "RO-043",
    name: "Pinealon",
    category: "cognitive",
    description: "Tripeptide bioregulator (Glu-Asp-Arg)",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 141.4,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/pinealon/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Pinealon_5mg-1024x1024.webp",
    icon: "Brain",
  },
  {
    id: "selank",
    sku: "RO-039",
    name: "Selank",
    category: "cognitive",
    description: "Tuftsin analogue heptapeptide",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 141.4,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/selank/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Selank_5mg-1024x1024.webp",
    icon: "Brain",
  },
  {
    id: "semax",
    sku: "RO-037",
    name: "Semax",
    category: "cognitive",
    description: "ACTH(4-10) analogue heptapeptide",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 148.0,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/semax/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Semax_5mg-1024x1024.webp",
    icon: "Brain",
  },
  {
    id: "semaglutide",
    sku: "RO-001",
    name: "Semaglutide",
    category: "weightloss",
    description: "GLP-1 receptor agonist analogue",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 126.0,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/semaglutide/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Semaglutide_2mg-1024x1024.webp",
    icon: "Flame",
  },
  {
    id: "cjc-1295-dac",
    sku: "RO-028",
    name: "CJC-1295 DAC",
    category: "recovery",
    description: "GHRH analogue with drug-affinity complex",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 396.6,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/cjc-1295-dac/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/CJC1295DAC_5mg-1024x1024.webp",
    icon: "Hexagon",
  },
  {
    id: "cjc-1295-no-dac",
    sku: "RO-027",
    name: "CJC-1295 (No DAC)",
    category: "recovery",
    description: "GHRH analogue (Mod GRF 1-29)",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 238.2,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/cjc-1295-no-dac/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/CJC1295-5mg-1024x1024.webp",
    icon: "Hexagon",
  },
  {
    id: "thymosin-alpha-1",
    sku: "RO-023",
    name: "Thymosin Alpha-1",
    category: "recovery",
    description: "Immunomodulatory thymic peptide",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 167.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/thymosin-alpha-1/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/ThymosinAlpha1_2mg-1024x1024.webp",
    icon: "Shield",
  },
  {
    id: "ghk-cu",
    sku: "RO-020",
    name: "GHK-Cu",
    category: "recovery",
    description: "Copper tripeptide GHK-Cu",
    kitLabel: "10 Vials",
    dosage: "50mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 130.4,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/ghk-cu/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/GHKCu_50mg-1024x1024.webp",
    icon: "Sparkle",
  },
  {
    id: "bpc-157",
    sku: "RO-014",
    name: "BPC-157",
    category: "recovery",
    description: "Body-protection compound (pentadecapeptide)",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 123.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/bpc-157/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/BPC157_2mg-1024x1024.webp",
    icon: "Dna",
  },
  {
    id: "mots-c",
    sku: "RO-011",
    name: "MOTS-c",
    category: "weightloss",
    description: "Mitochondrial-derived peptide",
    kitLabel: "10 Vials",
    dosage: "10mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 187.6,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/mots-c/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/MOTSc_10mg-1024x1024.webp",
    icon: "Cpu",
  },
  {
    id: "aod-9604",
    sku: "RO-009",
    name: "AOD-9604",
    category: "weightloss",
    description: "hGH fragment 177-191 analogue",
    kitLabel: "10 Vials",
    dosage: "2mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 165.6,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/aod-9604/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/AOD9604_2mg-1024x1024.webp",
    icon: "Flame",
  },
  {
    id: "cagrilintide",
    sku: "RO-004",
    name: "Cagrilintide",
    category: "weightloss",
    description: "Long-acting amylin analogue",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 291.0,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/cagrilintide/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Cagrilintide_5mg-1024x1024.webp",
    icon: "Flame",
  },
  {
    id: "retatrutide",
    sku: "RO-003",
    name: "Retatrutide",
    category: "weightloss",
    description: "Triple GIP/GLP-1/glucagon agonist",
    kitLabel: "10 Vials",
    dosage: "5mg",
    purity: ">99%",
    form: "Lyophilized",
    priceFrom: 167.8,
    priceIsFrom: true,
    inStock: true,
    researchUseOnly: true,
    partnerUrl: "https://researchonly.io/product/retatrutide/",
    imageUrl: "https://researchonly.io/wp-content/uploads/2026/06/Retatrutide_5mg-1024x1024.webp",
    icon: "Flame",
  },
];

export type PartnerLab = {
  id: string;
  name: string;
  verified: boolean;
  region: string;
  shipTime: string;
  freeShipping: boolean;
  purity: string;
  testing: string;
  productCount: number;
  shopUrl: string;
  aboutUrl: string;
  disclaimer: string;
};

export const PARTNER_LAB: PartnerLab = {
  id: "research-only",
  name: RESEARCH_ONLY.name,
  verified: true,
  region: RESEARCH_ONLY.region,
  shipTime: RESEARCH_ONLY.shipping,
  freeShipping: true,
  purity: RESEARCH_ONLY.purity,
  testing: RESEARCH_ONLY.testing,
  productCount: PEPTIDES.length,
  shopUrl: RESEARCH_ONLY.shopUrl,
  aboutUrl: RESEARCH_ONLY.aboutUrl,
  disclaimer: RESEARCH_ONLY.disclaimer,
};

/** @deprecated multi-lab mock removed; single partner is Research Only */
export type Lab = PartnerLab;
export const LABS: PartnerLab[] = [PARTNER_LAB];

export const MARKETPLACE_STATS = {
  peptidesListed: String(PEPTIDES.length),
  partnerLab: MARKETPLACE_BRAND.name,
  purity: RESEARCH_ONLY.purity,
  kitNote: "10-vial kits",
  shipping: "USDC on-chain",
};

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: "Browse the catalog",
    description: "Filter compounds by research area",
  },
  {
    step: 2,
    title: "Pay in USDC",
    description: "Buy a kit on Robinhood testnet at the listed price",
  },
  {
    step: 3,
    title: "Receive kit NFT",
    description: "Get a PEPT-KIT voucher; redeem later for the physical peptide",
  },
];

export function formatPrice(p: Peptide): string {
  const prefix = p.priceIsFrom ? "from " : "";
  return `${prefix}$${p.priceFrom.toFixed(2)}`;
}

export function categoryCounts(): Record<string, number> {
  const counts: Record<string, number> = { all: PEPTIDES.length };
  for (const p of PEPTIDES) {
    counts[p.category] = (counts[p.category] ?? 0) + 1;
  }
  return counts;
}
